import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  BrainCircuit,
  ShieldCheck,
  BarChart2,
  Target,
  ArrowRight,
  Sparkles,
  TrendingUp,
  CheckCircle2,
  ChevronRight,
  Zap,
  Globe,
} from 'lucide-react';

/* ─── Animated canvas background ─────────────────────────────── */
function ParticleCanvas() {
  const canvasRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    let animId;

    const resize = () => {
      canvas.width = canvas.offsetWidth;
      canvas.height = canvas.offsetHeight;
    };
    resize();
    window.addEventListener('resize', resize);

    const PARTICLE_COUNT = 70;
    const particles = Array.from({ length: PARTICLE_COUNT }, () => ({
      x: Math.random() * canvas.width,
      y: Math.random() * canvas.height,
      r: Math.random() * 1.8 + 0.4,
      dx: (Math.random() - 0.5) * 0.35,
      dy: (Math.random() - 0.5) * 0.35,
      opacity: Math.random() * 0.5 + 0.1,
    }));

    const draw = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const dx = particles[i].x - particles[j].x;
          const dy = particles[i].y - particles[j].y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 120) {
            ctx.beginPath();
            ctx.strokeStyle = `rgba(99,102,241,${0.12 * (1 - dist / 120)})`;
            ctx.lineWidth = 0.6;
            ctx.moveTo(particles[i].x, particles[i].y);
            ctx.lineTo(particles[j].x, particles[j].y);
            ctx.stroke();
          }
        }
      }
      particles.forEach((p) => {
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(139,92,246,${p.opacity})`;
        ctx.fill();
        p.x += p.dx;
        p.y += p.dy;
        if (p.x < 0 || p.x > canvas.width)  p.dx *= -1;
        if (p.y < 0 || p.y > canvas.height) p.dy *= -1;
      });
      animId = requestAnimationFrame(draw);
    };
    draw();

    return () => {
      cancelAnimationFrame(animId);
      window.removeEventListener('resize', resize);
    };
  }, []);

  return <canvas ref={canvasRef} className="absolute inset-0 w-full h-full pointer-events-none" />;
}

/* ─── Animated counter ───────────────────────────────────────── */
function Counter({ to, suffix = '' }) {
  const [val, setVal] = useState(0);
  useEffect(() => {
    let start = 0;
    const step = Math.ceil(to / 60);
    const timer = setInterval(() => {
      start += step;
      if (start >= to) { setVal(to); clearInterval(timer); }
      else setVal(start);
    }, 20);
    return () => clearInterval(timer);
  }, [to]);
  return <>{val.toLocaleString()}{suffix}</>;
}

/* ─── Feature card ───────────────────────────────────────────── */
function FeatureCard({ icon: Icon, title, desc, gradient, glow, path, delay }) {
  return (
    // animationDelay is a computed JS value, must stay inline
    <Link to={path} className="no-underline group" style={{ animationDelay: delay }}>
      <div className="landing-card relative flex flex-col h-full rounded-[20px] p-7 overflow-hidden
        bg-[rgba(15,23,42,0.7)] border border-white/[0.08] backdrop-blur-[20px]
        transition-[transform,box-shadow] duration-300">

        {/* Gradient overlay on hover — gradient is dynamic prop, opacity driven by CSS class */}
        <div
          className="card-gradient-overlay absolute inset-0 rounded-[20px] opacity-0 transition-opacity duration-300 z-0"
          style={{ background: gradient }}
        />

        {/* Glow blob — glow is a dynamic colour prop */}
        <div
          className="absolute -top-[30px] -right-[30px] w-[120px] h-[120px] rounded-full opacity-25 blur-[40px] transition-opacity duration-300 pointer-events-none"
          style={{ background: glow }}
        />

        {/* Icon — gradient is dynamic */}
        <div
          className="relative z-[1] w-[52px] h-[52px] rounded-[14px] flex items-center justify-center mb-[18px]"
          style={{ background: gradient, boxShadow: `0 8px 24px ${glow}60` }}
        >
          <Icon size={22} color="white" />
        </div>

        <h3 className="relative z-[1] text-[16px] font-bold text-[#f1f5f9] mb-2.5">
          {title}
        </h3>
        <p className="card-explore-target relative z-[1] flex-1 text-[13.5px] text-slate-400/85 leading-[1.65]">
          {desc}
        </p>

        <div className="card-explore relative z-[1] mt-5 flex items-center gap-[5px] text-[12px] font-bold text-violet-400 opacity-0 transition-opacity duration-[0.25s]">
          Explore <ChevronRight size={13} />
        </div>
      </div>
    </Link>
  );
}

const FEATURES = [
  {
    icon: BrainCircuit,
    title: 'AI Advisor',
    desc: 'Institutional-grade portfolio allocation generated by AI, validated with Zod, and tailored to your exact income and risk profile.',
    gradient: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
    glow: '#6366f1',
    path: '/signup',
  },
  {
    icon: Target,
    title: 'Finance Goals',
    desc: 'Plan for retirement, a new home, or education. See exactly when you will hit each milestone with precision.',
    gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
    glow: '#f59e0b',
    path: '/signup',
  },
  {
    icon: ShieldCheck,
    title: 'Risk Analysis',
    desc: 'Deep dive into asset class volatility. Compare India vs US market risks using 5-year historical data.',
    gradient: 'linear-gradient(135deg,#ec4899,#f43f5e)',
    glow: '#ec4899',
    path: '/signup',
  },
  {
    icon: BarChart2,
    title: 'Market Data',
    desc: 'Real-time tracking of top-performing stocks and commodities across global exchanges.',
    gradient: 'linear-gradient(135deg,#10b981,#059669)',
    glow: '#10b981',
    path: '/signup',
  },
];

const STATS = [
  { label: 'Active Investors',    value: 12800, suffix: '+' },
  { label: 'Portfolios Analysed', value: 54000, suffix: '+' },
  { label: 'Markets Covered',     value: 180,   suffix: '' },
  { label: 'AI Accuracy',         value: 94,    suffix: '%' },
];

const TRUST_POINTS = [
  'AI-personalised portfolio allocation',
  'Zod-validated structured AI responses',
  'India & US market coverage',
  'Save and review advisory history',
];

/* ─── Ticker ─────────────────────────────────────────────────── */
const TICKER = [
  { sym: 'NIFTY 50',  val: '24,832', chg: '+1.2%', up: true  },
  { sym: 'S&P 500',   val: '5,614',  chg: '+0.8%', up: true  },
  { sym: 'BTC/USD',   val: '$67,420',chg: '-0.3%', up: false },
  { sym: 'GOLD',      val: '$2,314', chg: '+0.5%', up: true  },
  { sym: 'SENSEX',    val: '81,954', chg: '+1.4%', up: true  },
  { sym: 'NASDAQ',    val: '19,230', chg: '+1.1%', up: true  },
  { sym: 'CRUDE OIL', val: '$82.4',  chg: '-0.6%', up: false },
];

export default function LandingPage() {
  return (
    <>
      {/* ── Global styles injected once ─────────────────────── */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');

        .landing-root * { box-sizing: border-box; }
        .landing-root { font-family: 'Inter', sans-serif; }

        .landing-card:hover { transform: translateY(-6px); box-shadow: 0 20px 60px rgba(0,0,0,0.4); }
        .landing-card:hover .card-explore { opacity: 1 !important; }
        .landing-card:hover .card-gradient-overlay { opacity: 0.08 !important; }

        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-18px); }
        }
        @keyframes pulse-glow {
          0%, 100% { opacity: 0.4; }
          50% { opacity: 0.75; }
        }
        @keyframes ticker-scroll {
          0% { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        @keyframes fade-up {
          from { opacity: 0; transform: translateY(24px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes shimmer {
          0% { background-position: -200% center; }
          100% { background-position: 200% center; }
        }
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }

        .anim-fade-up { animation: fade-up 0.7s ease forwards; opacity: 0; }
        .ticker-inner { animation: ticker-scroll 30s linear infinite; display: flex; gap: 0; }
        .ticker-inner:hover { animation-play-state: paused; }

        .btn-primary {
          display: inline-flex; align-items: center; gap: 8px;
          padding: 14px 30px;
          background: linear-gradient(135deg, #6366f1, #8b5cf6);
          color: white; font-weight: 700; font-size: 14px;
          border: none; border-radius: 14px; cursor: pointer;
          box-shadow: 0 8px 32px rgba(99,102,241,0.45);
          transition: transform 0.2s, box-shadow 0.2s;
          text-decoration: none;
        }
        .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 12px 40px rgba(99,102,241,0.6); }
        .btn-primary:active { transform: scale(0.97); }

        .btn-secondary {
          display: inline-flex; align-items: center; gap: 8px;
          padding: 14px 30px;
          background: rgba(255,255,255,0.06);
          color: #e2e8f0; font-weight: 700; font-size: 14px;
          border: 1px solid rgba(255,255,255,0.12); border-radius: 14px; cursor: pointer;
          backdrop-filter: blur(12px);
          transition: transform 0.2s, background 0.2s;
          text-decoration: none;
        }
        .btn-secondary:hover { transform: translateY(-2px); background: rgba(255,255,255,0.1); }

        .shimmer-text {
          background: linear-gradient(90deg, #a78bfa, #818cf8, #60a5fa, #a78bfa);
          background-size: 200% auto;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          animation: shimmer 3s linear infinite;
        }

        .orb {
          position: absolute; border-radius: 50%;
          filter: blur(80px); pointer-events: none;
          animation: pulse-glow 6s ease-in-out infinite;
        }

        .stat-card {
          background: rgba(15,23,42,0.6);
          border: 1px solid rgba(255,255,255,0.07);
          border-radius: 16px;
          padding: 20px 24px;
          text-align: center;
          backdrop-filter: blur(12px);
          transition: transform 0.3s ease;
        }
        .stat-card:hover { transform: translateY(-4px); }

        .nav-glass {
          background: rgba(7,11,31,0.8);
          border-bottom: 1px solid rgba(255,255,255,0.06);
          backdrop-filter: blur(24px);
        }
      `}</style>

      <div className="landing-root min-h-screen bg-[#060b18] text-[#f1f5f9] overflow-x-hidden">

        {/* ── Nav ─────────────────────────────────────────────── */}
        <nav className="nav-glass sticky top-0 z-50 h-16">
          <div className="max-w-[1100px] mx-auto h-full flex items-center justify-between px-6 md:px-10">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-[10px] flex items-center justify-center shadow-[0_0_20px_rgba(16,185,129,0.4)]"
              style={{ background: 'linear-gradient(135deg,#10b981,#059669)' }}>
              <svg width="16" height="16" fill="none" stroke="white" strokeWidth="2.4" viewBox="0 0 24 24">
                <path d="M3 3v18h18"/><path d="m19 9-5 5-4-4-3 3"/>
              </svg>
            </div>
            <div>
              <span className="text-[14px] font-extrabold text-[#f1f5f9] tracking-[-0.3px]">Global Wealth</span>
              <span className="text-[10.5px] text-slate-400/50 ml-2 font-medium">AI Investment Advisor</span>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <Link to="/login" className="no-underline">
              <button className="px-[18px] py-2 bg-transparent border border-white/[0.12] rounded-[10px] text-[#cbd5e1] text-[13px] font-semibold cursor-pointer transition-all hover:bg-white/[0.06]">
                Log In
              </button>
            </Link>
            <Link to="/signup" className="no-underline">
              <button
                className="px-[18px] py-2 border-none rounded-[10px] text-white text-[13px] font-bold cursor-pointer transition-all hover:-translate-y-px"
                style={{ background: 'linear-gradient(135deg,#6366f1,#8b5cf6)', boxShadow: '0 4px 16px rgba(99,102,241,0.35)' }}
              >
                Get Started
              </button>
            </Link>
          </div>
          </div>
        </nav>

        {/* ── Ticker bar ──────────────────────────────────────── */}
        <div className="bg-indigo-500/[0.08] border-b border-indigo-500/[0.15] overflow-hidden h-9 flex items-center">
          <div className="ticker-inner">
            {[...TICKER, ...TICKER].map((t, i) => (
              <div key={i} className="flex items-center gap-1.5 px-7 whitespace-nowrap border-r border-white/[0.05]">
                <span className="text-[11px] font-bold text-slate-400/70 tracking-[0.05em]">{t.sym}</span>
                <span className="text-[11px] font-semibold text-[#f1f5f9]">{t.val}</span>
                <span className={`text-[10.5px] font-bold ${t.up ? 'text-emerald-500' : 'text-red-500'}`}>{t.chg}</span>
              </div>
            ))}
          </div>
        </div>

        {/* ── Hero ─────────────────────────────────────────────── */}
        <section className="relative pt-[72px] pb-[64px] px-6 md:px-10 max-w-[1100px] mx-auto text-center overflow-hidden">
          {/* Particle canvas */}
          <div className="absolute inset-[-100px] overflow-hidden">
            <ParticleCanvas />
          </div>

          {/* Orbs */}
          <div className="orb" style={{ width: 500, height: 500, background: 'rgba(99,102,241,0.15)', top: -100, left: '10%' }} />
          <div className="orb" style={{ width: 400, height: 400, background: 'rgba(139,92,246,0.12)', top: 0, right: '10%', animationDelay: '2s' }} />
          <div className="orb" style={{ width: 300, height: 300, background: 'rgba(16,185,129,0.08)', bottom: 0, left: '30%', animationDelay: '4s' }} />

          <div className="relative z-[2]">
            {/* Badge */}
            <div className="anim-fade-up inline-flex items-center gap-[7px] px-4 py-[7px] mb-7
              bg-indigo-500/[0.12] border border-indigo-500/30 rounded-full
              text-[11px] font-bold text-violet-400 tracking-[0.12em] uppercase">
              <Sparkles size={11} />
              AI-Powered Wealth Management
              <Sparkles size={11} />
            </div>

            {/* Headline */}
            <h1 className="anim-fade-up text-[clamp(2.4rem,6vw,4.2rem)] font-black leading-[1.08] tracking-[-0.03em] mb-6 text-[#f8fafc]"
              style={{ animationDelay: '0.1s' }}>
              Invest smarter with<br />
              <span className="shimmer-text">AI-driven advice</span>
            </h1>

            {/* Sub */}
            <p className="anim-fade-up text-[clamp(1rem,2vw,1.2rem)] text-slate-400/85 max-w-[620px] mx-auto mb-10 leading-[1.7]"
              style={{ animationDelay: '0.2s' }}>
              Institutional-grade portfolio allocation, risk analysis, and financial goal planning —
              powered by AI and personalised for your income, risk, and timeline.
            </p>

            {/* CTA buttons */}
            <div className="anim-fade-up flex flex-wrap items-center justify-center gap-[14px] mb-10"
              style={{ animationDelay: '0.3s' }}>
              <Link to="/signup" className="btn-primary">
                Start for Free <ArrowRight size={16} />
              </Link>
              <Link to="/login" className="btn-secondary">
                Sign In
              </Link>
            </div>

            {/* Trust bullets */}
            <div className="anim-fade-up flex flex-wrap justify-center gap-x-6 gap-y-2"
              style={{ animationDelay: '0.4s' }}>
              {TRUST_POINTS.map((p) => (
                <span key={p} className="flex items-center gap-1.5 text-[12px] text-slate-400/70 font-medium">
                  <CheckCircle2 size={13} color="#10b981" />
                  {p}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* ── Stats ────────────────────────────────────────────── */}
        <section className="px-6 md:px-10 pb-[64px] max-w-[1100px] mx-auto">
          <div className="grid grid-cols-[repeat(auto-fit,minmax(180px,1fr))] gap-4">
            {STATS.map((s) => (
              <div key={s.label} className="stat-card">
                <div className="text-[clamp(1.6rem,4vw,2.2rem)] font-black text-[#f8fafc] tracking-[-0.03em] leading-[1.1] mb-1.5">
                  <Counter to={s.value} suffix={s.suffix} />
                </div>
                <div className="text-[12px] text-slate-400/60 font-medium uppercase tracking-[0.07em]">{s.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Feature cards ────────────────────────────────────── */}
        <section className="px-6 md:px-10 pb-[64px] max-w-[1100px] mx-auto">
          <div className="text-center mb-12">
            <p className="text-[11px] font-bold text-indigo-500 tracking-[0.14em] uppercase mb-2.5">
              Platform Modules
            </p>
            <h2 className="text-[clamp(1.6rem,4vw,2.4rem)] font-black text-[#f8fafc] tracking-[-0.03em] leading-[1.1]">
              Everything you need to invest wisely
            </h2>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-5">
            {FEATURES.map((f, i) => (
              <FeatureCard key={f.title} {...f} delay={`${i * 0.08}s`} />
            ))}
          </div>
        </section>

        {/* ── Dark CTA ─────────────────────────────────────────── */}
        <section className="px-6 md:px-10 pb-[64px] max-w-[1100px] mx-auto">
          <div className="relative rounded-[28px] text-center overflow-hidden
            border border-white/[0.06] shadow-[0_40px_100px_rgba(0,0,0,0.5)]"
            style={{ background: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)', padding: 'clamp(40px,8vw,72px)' }}>
            {/* Decorative glows */}
            <div className="absolute -top-[60px] -right-[60px] w-[300px] h-[300px] rounded-full bg-emerald-500/[0.12] blur-[60px] pointer-events-none" />
            <div className="absolute -bottom-[60px] -left-[60px] w-[300px] h-[300px] rounded-full bg-indigo-500/[0.12] blur-[60px] pointer-events-none" />
            <div className="absolute top-5 right-5 opacity-[0.04]">
              <TrendingUp size={200} />
            </div>
            {/* Spinning ring */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2
              w-[500px] h-[500px] rounded-full border border-indigo-500/[0.12] pointer-events-none"
              style={{ animation: 'spin-slow 20s linear infinite' }}
            />

            <div className="relative z-[2]">
              <div className="flex items-center justify-center gap-2 mb-4">
                <Zap size={14} color="#fbbf24" fill="#fbbf24" />
                <p className="text-[11px] font-bold text-emerald-500 tracking-[0.14em] uppercase">Ready to start?</p>
              </div>
              <h2 className="text-[clamp(1.8rem,5vw,3rem)] font-black text-[#f8fafc] tracking-[-0.03em] leading-[1.08] mb-4">
                Your AI portfolio advisor<br />is waiting.
              </h2>
              <p className="text-slate-400/70 max-w-[480px] mx-auto mb-9 text-[15px] leading-[1.7]">
                Join thousands of investors getting AI-personalised allocation advice. Free to start.
              </p>
              <Link to="/signup" className="btn-primary">
                Create Free Account <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </section>

        {/* ── Footer ───────────────────────────────────────────── */}
        <footer className="border-t border-white/[0.05] py-5">
          <div className="max-w-[1100px] mx-auto px-6 md:px-10 flex flex-wrap justify-between items-center gap-3">
          <div className="flex items-center gap-2">
            <Globe size={13} color="rgba(148,163,184,0.4)" />
            <span className="text-[11px] text-slate-400/40 font-medium tracking-[0.05em] uppercase">
              Global Wealth Management © 2025
            </span>
          </div>
          <div className="flex gap-6">
            {['Privacy Policy', 'Risk Disclosure', 'Terms'].map((l) => (
              <button
                key={l}
                className="bg-transparent border-none cursor-pointer text-[11px] text-slate-400/40 font-medium tracking-[0.05em] uppercase transition-colors hover:text-slate-400"
              >
                {l}
              </button>
            ))}
          </div>
          </div>
        </footer>
      </div>
    </>
  );
}
